### ISSUE TITLE
Use keypad keycodes in ncurses

### ISSUE THREAD

**Issue by MisterDA** [ulfalizer/readline-and-ncurses#1]
Hello !
Your code has greatly helped me to intergrate readline in ncurses for a student project.
I would like to replicate an irssi interface for an IRC-like protocol.
I want to catch keypresses events (like F(n) keys, or shift-arrow combinaisons) in the ncurses part and not forward them to readline. The catching is done with `keypad`, but as you wrote:
> Do not enable keypad() since we want to pass unadulterated input to readline

How can I handle special keys events in the ncurses scope, while passing unadulterated input to readline ? Is is possible ? Maybe with a inverse transformation ?
What if I do `keypad`, then test if its a special char, if so disable `keypad` and somehow `ungetch` the character ?

Or is the only solution to wait and watch for the sequence of unadulterated input ? [ncurses.faq.html#modified_keys](http://invisible-island.net/ncurses/ncurses.faq.html#modified_keys)

Thank you for your time.

PS: can I use your code ? Is is MIT licensed ?

**Comment by MisterDA** [comment]
I posted an almost identical [question](https://stackoverflow.com/questions/41127796/readline-ncurses-handle-special-keys-and-keys-combinations) on stackoverflow.
The idea seems to let readline do the bindings & callbacks.

Thank you anyway for the good work !

**Comment by ulfalizer** [comment]
Glad it's helpful. Feel free to use it! It's public domain to me.

Yeah, things get a bit messy with `keypad()` enabled. The only method I'm aware of would be to translate symbolic constants like `KEY_RIGHT` back to escape sequences and feed those to readline. To get the correct escape sequence for the terminal, you can do e.g. `tigetstr("kcuf1")`, where `terminfo(5)` lists the capability names (`kcuf1` is the right arrow key). In practice, you're very likely to be dealing with a terminal that uses ANSI escape sequences.

Handling it inside readline is probably easiest, like you said. I'd start with that.
